language: php
php:
  - 7.1
  - 7.2

before_script:
  - composer self-update
  - composer install

script:
  - mkdir -p build/logs
  - vendor/bin/phpunit

after_scripts:
  - travis_retry php vendor/bin/coveralls -v
